CREATE TABLE urls (
  id VARCHAR(4) PRIMARY KEY NOT NULL,
  url TEXT NOT NULL,
  creator INTEGER,
  created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(creator) REFERENCES admins(id) ON DELETE SET NULL
)
